lib/hider_web/router.ex
defmodule HiderWeb.Router do
  use HiderWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {HiderWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", HiderWeb do
    pipe_through :browser

    live "/users", UserLive.Index, :index
    live "/users/new", UserLive.Index, :new
    live "/users/:id/edit", UserLive.Index, :edit

    live "/users/:id", UserLive.Show, :show
    live "/users/:id/show/edit", UserLive.Show, :edit
  end

  # Other scopes may use custom stacks.
  scope "/api", HiderWeb do
    pipe_through :api

    resources "/users", UserController, except: [:new, :edit]
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: HiderWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/hider_web/live/live_helpers.ex
defmodule HiderWeb.LiveHelpers do
  import Phoenix.LiveView
  import Phoenix.LiveView.Helpers

  alias Phoenix.LiveView.JS

  @doc """
  Renders a live component inside a modal.

  The rendered modal receives a `:return_to` option to properly update
  the URL when the modal is closed.

  ## Examples

      <.modal return_to={Routes.user_index_path(@socket, :index)}>
        <.live_component
          module={HiderWeb.UserLive.FormComponent}
          id={@user.id || :new}
          title={@page_title}
          action={@live_action}
          return_to={Routes.user_index_path(@socket, :index)}
          user: @user
        />
      </.modal>
  """
  def modal(assigns) do
    assigns = assign_new(assigns, :return_to, fn -> nil end)

    ~H"""
    <div id="modal" class="phx-modal fade-in" phx-remove={hide_modal()}>
      <div
        id="modal-content"
        class="phx-modal-content fade-in-scale"
        phx-click-away={JS.dispatch("click", to: "#close")}
        phx-window-keydown={JS.dispatch("click", to: "#close")}
        phx-key="escape"
      >
        <%= if @return_to do %>
          <%= live_patch "✖",
            to: @return_to,
            id: "close",
            class: "phx-modal-close",
            phx_click: hide_modal()
          %>
        <% else %>
         <a id="close" href="#" class="phx-modal-close" phx-click={hide_modal()}>✖</a>
        <% end %>

        <%= render_slot(@inner_block) %>
      </div>
    </div>
    """
  end

  defp hide_modal(js \\ %JS{}) do
    js
    |> JS.hide(to: "#modal", transition: "fade-out")
    |> JS.hide(to: "#modal-content", transition: "fade-out-scale")
  end
end

lib/hider_web/live/user_live/form_component.ex
defmodule HiderWeb.UserLive.FormComponent do
  use HiderWeb, :live_component

  alias Hider.Accounts

  @impl true
  def update(%{user: user} = assigns, socket) do
    changeset = Accounts.change_user(user)

    socket
    |> assign(assigns)
    |> assign(:changeset, changeset)
    |> then(&{:ok, &1})
  end

  @impl true
  def handle_event("validate", %{"user" => user_params}, socket) do
    changeset =
      socket.assigns.user
      |> Accounts.change_user(parse_user_params(user_params))
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"user" => user_params}, socket) do
    save_user(socket, socket.assigns.action, user_params)
  end

  defp parse_user_params(user_params) do
    only_digits = &String.replace(&1, ~r/[^0-9]/, "")

    user_params
    |> Map.update("cpf", "", only_digits)
    |> Map.update("rg", "", only_digits)
  end

  defp save_user(socket, :edit, user_params) do
    user_params = parse_user_params(user_params)

    case Accounts.update_user(socket.assigns.user, user_params) do
      {:ok, _user} ->
        socket
        |> put_flash(:info, "User updated successfully")
        |> push_redirect(to: socket.assigns.return_to)
        |> then(&{:noreply, &1})

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_user(socket, :new, user_params) do
    case Accounts.create_user(user_params) do
      {:ok, _user} ->
        socket
        |> put_flash(:info, "User created successfully")
        |> push_redirect(to: socket.assigns.return_to)
        |> then(&{:noreply, &1})

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/hider_web/live/user_live/index.ex
defmodule HiderWeb.UserLive.Index do
  use HiderWeb, :live_view

  alias Hider.Accounts
  alias Hider.Accounts.User
  import HiderWeb.UserView

  @impl true
  def mount(_params, _session, socket) do
    users = list_users() |> decrypt()

    socket
    |> assign(:users, list_users() |> Enum.map(&User.decrypt(&1, :all)))
    |> assign(:search, %{search: ""})
    |> then(fn socket -> {:ok, socket} end)
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    user = id |> Accounts.get_user!() |> decrypt()

    socket
    |> assign(:page_title, "Edit User")
    |> assign(:user, Accounts.get_user!(id) |> User.decrypt(:all))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New User")
    |> assign(:user, %User{})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Users")
    |> assign(:user, nil)
  end

  def handle_event("search", %{"search" => %{"search" => search}}, socket) do
    search
    |> search()
    |> Enum.map(&User.decrypt(&1, :all))
    |> then(&{:noreply, assign(socket, :users, &1)})
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    user = Accounts.get_user!(id)
    {:ok, _} = Accounts.delete_user(user)

    {:noreply, assign(socket, :users, list_users() |> Enum.map(&User.decrypt(&1, :all)))}
  end

  defp list_users do
    Accounts.list_users()
  end

  defp search(search) do
    Accounts.fuzzy_search(search)
  end
end

lib/hider_web/live/user_live/show.ex
defmodule HiderWeb.UserLive.Show do
  use HiderWeb, :live_view

  alias Hider.Accounts
  import HiderWeb.UserView

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:user, id |> Accounts.get_user!() |> decrypt())
     |> then(&{:noreply, &1})
  end

  defp page_title(:show), do: "Show User"
  defp page_title(:edit), do: "Edit User"
end

lib/hider_web/live/user_live/form_component.html.heex
<div>
  <h2><%= @title %></h2>

  <.form
    let={f}
    for={@changeset}
    id="user-form"
    phx-target={@myself}
    phx-change="validate"
    phx-submit="save">
      
    <%= label f, :email %>
    <%= text_input f, :email %>
    <%= error_tag f, :email %>

    <%= label f, :username %>
    <%= text_input f, :username %>
    <%= error_tag f, :username %>
  
    <%= label f, :first_name %>
    <%= text_input f, :first_name %>
    <%= error_tag f, :first_name %>
  
    <%= label f, :middle_name %>
    <%= text_input f, :middle_name %>
    <%= error_tag f, :middle_name %>
  
    <%= label f, :last_name %>
    <%= text_input f, :last_name %>
    <%= error_tag f, :last_name %>
  
    <%= label f, :cpf %>
    <%= text_input f, :cpf %>
    <%= error_tag f, :cpf %>
  
    <%= label f, :rg %>
    <%= text_input f, :rg %>
    <%= error_tag f, :rg %>
  
    <%= label f, :password %>
    <%= password_input f, :password, value: input_value(f, :password) %>
    <%= error_tag f, :password %>

    <%= password_input f, :password_confirmation, value: input_value(f, :password_confirmation) %>
    <%= error_tag f, :password_confirmation %>

    <div>
      <%= submit "Save", phx_disable_with: "Saving..." %>
    </div>
  </.form>
</div>

lib/hider_web/live/user_live/index.html.heex
<h1>Listing Users</h1>

<%= if @live_action in [:new, :edit] do %>
  <.modal return_to={Routes.user_index_path(@socket, :index)}>
    <.live_component
      module={HiderWeb.UserLive.FormComponent}
      id={@user.id || :new}
      title={@page_title}
      action={@live_action}
      user={@user}
      return_to={Routes.user_index_path(@socket, :index)}
    />
  </.modal>
<% end %>

<.form
  let={f}
  for={:search}
  id="search-form"
  phx-submit="search">
    
  <%= label f, :search %>
  <%= text_input f, :search %>

  <div>
    <%= submit "Search", phx_disable_with: "Searching..." %>
  </div>
</.form>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Middle name</th>
      <th>Last name</th>
      <th>Cpf</th>
      <th>Rg</th>

      <th></th>
    </tr>
  </thead>
  <tbody id="users">
    <%= for user <- @users do %>
      <tr id={"user-#{user.id}"}>
        <td><%= user.first_name %></td>
        <td><%= user.middle_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.cpf  %></td>
        <td><%= user.rg %></td>

        <td>
          <span><%= live_redirect "Show", to: Routes.user_show_path(@socket, :show, user) %></span>
          <span><%= live_patch "Edit", to: Routes.user_index_path(@socket, :edit, user) %></span>
          <span><%= link "Delete", to: "#", phx_click: "delete", phx_value_id: user.id, data: [confirm: "Are you sure?"] %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<span><%= live_patch "New User", to: Routes.user_index_path(@socket, :new) %></span>

lib/hider_web/live/user_live/show.html.heex
<h1>Show User</h1>

<%= if @live_action in [:edit] do %>
  <.modal return_to={Routes.user_show_path(@socket, :show, @user)}>
    <.live_component
      module={HiderWeb.UserLive.FormComponent}
      id={@user.id}
      title={@page_title}
      action={@live_action}
      user={@user}
      return_to={Routes.user_show_path(@socket, :show, @user)}
    />
  </.modal>
<% end %>

<ul>
  <li>
    <strong>Email:</strong>
    <%= @user.email %>
  </li>

  <li>
    <strong>Username:</strong>
    <%= @user.username %>
  </li>

  <li>
    <strong>First name:</strong>
    <%= @user.first_name %>
  </li>

  <li>
    <strong>Middle name:</strong>
    <%= @user.middle_name %>
  </li>

  <li>
    <strong>Last name:</strong>
    <%= @user.last_name %>
  </li>

  <li>
    <strong>Cpf:</strong>
    <%= @user.cpf %>
  </li>

  <li>
    <strong>Rg:</strong>
    <%= @user.rg %>
  </li>

</ul>

<span>
  <%= live_patch "Edit", to: Routes.user_show_path(@socket, :edit, @user), class: "button" %>
</span>

<span>
  <%= live_redirect "Back", to: Routes.user_index_path(@socket, :index) %>
</span>